// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpwBB-ZP4_66X1g0XbfLG1XTZJJackL2w',
    appId: '1:886012631288:web:8bc7774c5103a685f1030d',
    messagingSenderId: '886012631288',
    projectId: 'balpum-b18bd',
    authDomain: 'balpum-b18bd.firebaseapp.com',
    storageBucket: 'balpum-b18bd.appspot.com',
    measurementId: 'G-4XQT0JQR00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJri4hL52tGwsC_6CZu182Q6N5QQZXQcE',
    appId: '1:886012631288:android:c99ad32115d2b53cf1030d',
    messagingSenderId: '886012631288',
    projectId: 'balpum-b18bd',
    storageBucket: 'balpum-b18bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lArTWdO5NiHF5L0yVFLm-fHbWG0qwCk',
    appId: '1:886012631288:ios:03c143d6a2da653ff1030d',
    messagingSenderId: '886012631288',
    projectId: 'balpum-b18bd',
    storageBucket: 'balpum-b18bd.appspot.com',
    androidClientId: '886012631288-li22djen1av98ofd467cjmbj75gj8lho.apps.googleusercontent.com',
    iosClientId: '886012631288-mjpmrbrj0r01gu32kcim2i5olapp8g3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkDScvU0bFSRylR0Ndg0vD7xykBTkGy2g',
    appId: '1:886012631288:ios:db9e088026a3bcd0f1030d',
    messagingSenderId: '886012631288',
    projectId: 'balpum-b18bd',
    storageBucket: 'balpum-b18bd.appspot.com',
    iosBundleId: 'com.example.balpum.RunnerTests',
  );
}